### PR TITLE
Added comment section

### PR DESCRIPTION
**Pull request by iamfarhatsharefi**
Overview
This pull request enhances the visual appeal of the Roman Numeral Converter application by adding a background image. The update focuses on improving user experience and aligning with modern design practices.

Changes Made
CSS Enhancement: Integrated a background image to enrich the visual presentation of the application.
Accessibility Improvements: Ensured compatibility across different devices and screen sizes.
Code Optimization: Reviewed and refined existing CSS for cleaner and more efficient styling.
User Experience: Enhanced visual aesthetics to create a more engaging interface.
Testing and Validation
Visual Inspection: Verified the appearance and responsiveness of the background image across various devices.
Functionality Check: Ensured all functionality remains intact after the visual enhancement.
Cross-Browser Compatibility: Tested in multiple browsers to ensure consistent performance.
Impact and Benefits
Improved Aesthetics: Provides a visually appealing backdrop that enhances the overall user experience.
Modern Look and Feel: Aligns with contemporary design trends to maintain relevance and attractiveness.
Enhanced Usability: Supports user engagement by making the application more inviting and visually appealing.

### CODE REVIEW

**Comment by iamfarhatsharefi** [comment]
@Nooria150 @Saqibi4213
please review my code dears , your comment will be precious to me.

**Comment by Saqibi4213** [comment]
@iamfarhatsharefi

Great Design Implemented
✔ Created a professional Repo (You created a repository with your project name)
✔ Correct use of Gitflow (You created the development branch and made it your default branch, then created and committed your work on your feature branch)
✔ Commit messages are meaningful
✔ Setup the linters correctly (You added the correct linters config into your project according to the language you used on your code)
✔ No linter errors (All linters checks have been passed 🟢)
✔ You have followed the Roman numeral converter project task and committed using the command line
✔ Created the pull request (From your feature branch to the development branch you created a pull request and submitted the pull request link for review)
✔ Good PR description (You added a meaningful description to your PR about your work and the features you added on this pull request)
✔Your code is clean
✔Your repo has a professional README.md file

**Review by Nooria150 — APPROVED** [review]
hello @iamfarhatsharefi

Great Design Implemented
✔ Created a professional Repo (You created a repository with your project name)
✔ Correct use of Gitflow (You created the development branch and made it your default branch, then created and committed your work on your feature branch)
✔ Commit messages are meaningful
✔ Setup the linters correctly (You added the correct linters config into your project according to the language you used on your code)
✔ No linter errors (All linters checks have been passed 🟢)
✔ You have followed the Roman numeral converter project task and committed using the command line
✔ Created the pull request (From your feature branch to the development branch you created a pull request and submitted the pull request link for review)
✔ Good PR description (You added a meaningful description to your PR about your work and the features you added on this pull request)
✔Your code is clean
✔Your repo has a professional README.md file

**Review by ahzamir — APPROVED** [review]
### Hi @iamfarhatsharefi 🙋‍♀️,

> Excellent work! 💯 You have done a great job implementing all the project requirements. 🥳 Your feature is complete! Congratulations!!!🎊

- **[REQUIRED]** Share your project on this [GROUP](https://www.facebook.com/groups/kick-startdev), add a simple Proud Moment text and a screenshot of your project then besides that add your project link at the end of the text as a GitHub Source code reference and post.

- Share your Project on your LinkedIn account and add a proud moment text on it with a screenshot.

- Well Done great design Implemented. 🎯🎉👍
image

# Status: Approved ✅
There is nothing to say other than to merge your branch. 🎉🎯✅👍😊🥳

WinkThumbsUpGIF (2)

 ## Highlights 🌞

🎉 Great Design Implemented 
✔️ Created a professional Repo (You created a repository with your project name)
✔️ Correct use of Gitflow (You created the development branch and made it your default branch, then created and committed your work on your feature branch)
✔️ Commit messages are meaningful
✔️ Setup the linters correctly (You added the correct linters config into your project according to the language you used on your code)
✔️ No linter errors (All linters checks have been passed 🟢)
✔️ You have followed the Roman Numeral Converter project task and committed using the command line
✔️ Created the pull request (From your feature branch to the development branch you created a pull request and submitted the pull request link for review)
✔️ Good PR description (You added a meaningful description to your PR about your work and the features you added on this pull request)
✔️Your repo has a professional README.md file
✔️Your code is clean
✔️Your repo has been reviewed by your partners
✔️Your design is impressive and responsive

**Cheers 🥂 and Happy coding!!! 👯 Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me @ahzamir in your question so I can receive the notification.**

**Pull request merged**
